# Set theme
remote_theme: daviddarnes/alembic
#remote_theme: "mmistakes/minimal-mistakes@4.15.2"

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-include-cache

# Gem settings
sass:
  style: compressed
  sass_dir: _sass

paginate: 8 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # base url for jekyll mentions

compress_html:
  clippings: all
  
twitter:
  username: angelatamtweets # jekyll-seo-tag > Owners twitter username

author: Angela Tam # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Angela Tam # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/angelatamtweets
    - https://www.linkedin.com/in/angela-tam-2054813b/
    - https://github.com/angela-tam

# Site settings
url: 'angela-tam.github.io'
baseurl: ''
title: 'Angela Tam'
description: ''
permalink: pretty
logo: "/assets/img/logo.png"
avatarurl: "/assets/img/avatar.png"

# site verification
webmaster_verifications:
  google: lB694ugK6e26p5fJs37qYbdvaozzE4dr219OLEdjgAI

# Pagination
paginate: 5
# paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Projects: /blog/
  Photos: /gallery/
  Bagels: /bagel/

# Footer nav
# navigation_footer:
#   Back to top: "#top"

# Site credits
navigation_footer:
   Adopted Alembic Theme: https://alembic.darn.es/
#   Minimal Mistakes Theme: https://mmistakes.github.io

contact:
  email:      angela.tam08@gmail.com
  github:     https://github.com/angela-tam
  linkedin:   https://www.linkedin.com/in/angela-tam-2054813b/
  twitter:    https://twitter.com/angelatamtweets

# Collections
collections:
  posts:
    title: Projects
    output: true
    description: "Here are some of my completed and ongoing projects"
#     feature_text: |
#       Welcome to my blog
    feature_image: "/assets/img/home_cover.jpg"
    
  photos:
    title: Photos
    output: true
    description: "Here are some of my photographs"
    
  bagels:
    title: Bagels
    output: true
    description: "Here are some of my reviews about bagels"
    feature_image: "/assets/img/home_cover.jpg"

# defaults:
#   -
#     scope:
#       path: "/photos/index.html"
#     values:
#       text_width: false
